## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
drop_df = application_df.drop(columns=['EIN', 'NAME'])
drop_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
unique_counts = drop_df.nunique(axis=0)
unique_counts

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = drop_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = application_type_counts['T10']
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_gt_1 = classification_counts[classification_counts > 1]
classification_counts_gt_1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value_classification = classification_counts['C2100']
classifications_to_replace = classification_counts[classification_counts < cutoff_value_classification].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df.head()

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC,NAME_100 BLACK MEN OF AMERICA,NAME_100 BLACK MEN OF MEMPHIS INC,NAME_100 BLACK MEN OF WEST GEORGIA INC,NAME_1150 WEBSTER STREET INC,NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,10531628,1,108590,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,10547893,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,10553066,1,6692,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,10556103,1,142590,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
# Set the target column
y = dummies_df["IS_SUCCESSFUL"]

# Drop the target column from the original dataframe to get the features
X = dummies_df.drop(["IS_SUCCESSFUL"], axis=1)

In [11]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  14
hidden_nodes_layer2 = 28

nn_1 = tf.keras.models.Sequential()

# First hidden layer
nn_1.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn_1.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn_1.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 14)                274582

 dense_1 (Dense)             (None, 28)                420

 dense_2 (Dense)             (None, 1)                 29

=================================================================
Total params: 275031 (1.05 MB)
Trainable params: 275031 (1.05 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Compile the model
nn_1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [15]:
# Train the model
fit_model = nn_1.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 6s 5ms/step - loss: 0.4885 - accuracy: 0.7624
Epoch 2/100
804/804 [==============================] - 4s 5ms/step - loss: 0.2157 - accuracy: 0.9139
Epoch 3/100
804/804 [==============================] - 4s 5ms/step - loss: 0.1090 - accuracy: 0.9576
Epoch 4/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0987 - accuracy: 0.9605
Epoch 5/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0955 - accuracy: 0.9610
Epoch 6/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0939 - accuracy: 0.9617
Epoch 7/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0924 - accuracy: 0.9616
Epoch 8/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0914 - accuracy: 0.9624
Epoch 9/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0908 - accuracy: 0.9630
Epoch 10/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0898 - accuracy: 0.9632
Epoch 11/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0892 - accuracy: 0.9637
Epoch 12/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0888 - accuracy: 0.9628
Epoch 13/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0882 - accuracy: 0.9637
Epoch 14/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0873 - accuracy: 0.9642
Epoch 15/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0871 - accuracy: 0.9642
Epoch 16/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0869 - accuracy: 0.9638
Epoch 17/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0861 - accuracy: 0.9640
Epoch 18/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0861 - accuracy: 0.9644
Epoch 19/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0857 - accuracy: 0.9645
Epoch 20/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0848 - accuracy: 0.9643
Epoch 21/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0852 - accuracy: 0.9644
Epoch 22/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0846 - accuracy: 0.9651
Epoch 23/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0847 - accuracy: 0.9648
Epoch 24/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0838 - accuracy: 0.9648
Epoch 25/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0837 - accuracy: 0.9652
Epoch 26/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0841 - accuracy: 0.9648
Epoch 27/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0836 - accuracy: 0.9654
Epoch 28/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0834 - accuracy: 0.9650
Epoch 29/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0828 - accuracy: 0.9653
Epoch 30/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0831 - accuracy: 0.9653
Epoch 31/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0825 - accuracy: 0.9656
Epoch 32/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0819 - accuracy: 0.9658
Epoch 33/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0824 - accuracy: 0.9655
Epoch 34/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0821 - accuracy: 0.9657
Epoch 35/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0816 - accuracy: 0.9659
Epoch 36/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0813 - accuracy: 0.9661
Epoch 37/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0811 - accuracy: 0.9665
Epoch 38/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0813 - accuracy: 0.9662
Epoch 39/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0812 - accuracy: 0.9666
Epoch 40/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0809 - accuracy: 0.9665
Epoch 41/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0810 - accuracy: 0.9662
Epoch 42/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0805 - accuracy: 0.9668
Epoch 43/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0802 - accuracy: 0.9667
Epoch 44/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0803 - accuracy: 0.9665
Epoch 45/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0797 - accuracy: 0.9671
Epoch 46/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0797 - accuracy: 0.9669
Epoch 47/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0793 - accuracy: 0.9675
Epoch 48/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0795 - accuracy: 0.9669
Epoch 49/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0787 - accuracy: 0.9668
Epoch 50/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0790 - accuracy: 0.9674
Epoch 51/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0785 - accuracy: 0.9678
Epoch 52/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0792 - accuracy: 0.9672
Epoch 53/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0784 - accuracy: 0.9676
Epoch 54/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0785 - accuracy: 0.9680
Epoch 55/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0785 - accuracy: 0.9675
Epoch 56/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0785 - accuracy: 0.9674
Epoch 57/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0779 - accuracy: 0.9676
Epoch 58/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0777 - accuracy: 0.9678
Epoch 59/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0774 - accuracy: 0.9676
Epoch 60/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0774 - accuracy: 0.9679
Epoch 61/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0772 - accuracy: 0.9677
Epoch 62/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0771 - accuracy: 0.9682
Epoch 63/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0772 - accuracy: 0.9680
Epoch 64/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0769 - accuracy: 0.9682
Epoch 65/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0771 - accuracy: 0.9676
Epoch 66/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0774 - accuracy: 0.9681
Epoch 67/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0766 - accuracy: 0.9683
Epoch 68/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0765 - accuracy: 0.9680
Epoch 69/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0766 - accuracy: 0.9683
Epoch 70/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0767 - accuracy: 0.9686
Epoch 71/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0764 - accuracy: 0.9687
Epoch 72/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0761 - accuracy: 0.9682
Epoch 73/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0761 - accuracy: 0.9689
Epoch 74/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0765 - accuracy: 0.9686
Epoch 75/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0759 - accuracy: 0.9688
Epoch 76/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0760 - accuracy: 0.9683
Epoch 77/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0758 - accuracy: 0.9686
Epoch 78/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0759 - accuracy: 0.9686
Epoch 79/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0755 - accuracy: 0.9694
Epoch 80/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0756 - accuracy: 0.9684
Epoch 81/100

804/804 [==============================] - 4s 5ms/step - loss: 0.0757 - accuracy: 0.9683
Epoch 82/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0754 - accuracy: 0.9689
Epoch 83/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0751 - accuracy: 0.9690
Epoch 84/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0753 - accuracy: 0.9683
Epoch 85/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0756 - accuracy: 0.9689
Epoch 86/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0750 - accuracy: 0.9686
Epoch 87/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0751 - accuracy: 0.9685
Epoch 88/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0747 - accuracy: 0.9691
Epoch 89/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0751 - accuracy: 0.9690
Epoch 90/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0748 - accuracy: 0.9691
Epoch 91/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0745 - accuracy: 0.9688
Epoch 92/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0744 - accuracy: 0.9693
Epoch 93/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0744 - accuracy: 0.9687
Epoch 94/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0739 - accuracy: 0.9692
Epoch 95/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0741 - accuracy: 0.9688
Epoch 96/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0741 - accuracy: 0.9693
Epoch 97/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0744 - accuracy: 0.9694
Epoch 98/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0746 - accuracy: 0.9688
Epoch 99/100
804/804 [==============================] - 4s 6ms/step - loss: 0.0735 - accuracy: 0.9695
Epoch 100/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0734 - accuracy: 0.9694

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_1.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.6462 - accuracy: 0.7130 - 692ms/epoch - 3ms/step
Loss: 0.6461543440818787, Accuracy: 0.7130029201507568

In [17]:
# SECOND ATTEMPT
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  7
hidden_nodes_layer2 = 14

nn_2 = tf.keras.models.Sequential()

# First hidden layer
nn_2.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn_2.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn_2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 7)                 137291

 dense_4 (Dense)             (None, 14)                112

 dense_5 (Dense)             (None, 1)                 15

=================================================================
Total params: 137418 (536.79 KB)
Trainable params: 137418 (536.79 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
# Compile the model
nn_2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [19]:
# Train the model
fit_model = nn_2.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 3ms/step - loss: 0.6034 - accuracy: 0.7188
Epoch 2/100
804/804 [==============================] - 3s 3ms/step - loss: 0.3363 - accuracy: 0.8616
Epoch 3/100
804/804 [==============================] - 3s 3ms/step - loss: 0.1920 - accuracy: 0.9287
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.1568 - accuracy: 0.9409
Epoch 5/100
804/804 [==============================] - 3s 3ms/step - loss: 0.1175 - accuracy: 0.9575
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.1027 - accuracy: 0.9607
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0994 - accuracy: 0.9617
Epoch 8/100
804/804 [==============================] - 3s 3ms/step - loss: 0.0966 - accuracy: 0.9621
Epoch 9/100
804/804 [==============================] - 3s 3ms/step - loss: 0.0960 - accuracy: 0.9627
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0956 - accuracy: 0.9625
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0947 - accuracy: 0.9627
Epoch 12/100
804/804 [==============================] - 3s 3ms/step - loss: 0.0942 - accuracy: 0.9630
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0937 - accuracy: 0.9632
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0930 - accuracy: 0.9633
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0929 - accuracy: 0.9635
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.0924 - accuracy: 0.9640
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0919 - accuracy: 0.9642
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0915 - accuracy: 0.9640
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0907 - accuracy: 0.9649
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0910 - accuracy: 0.9639
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0900 - accuracy: 0.9645
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0905 - accuracy: 0.9647
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0899 - accuracy: 0.9650
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0898 - accuracy: 0.9649
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0889 - accuracy: 0.9652
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0889 - accuracy: 0.9649
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0888 - accuracy: 0.9649
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0886 - accuracy: 0.9646
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0888 - accuracy: 0.9659
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0884 - accuracy: 0.9658
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0881 - accuracy: 0.9649
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0884 - accuracy: 0.9659
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0882 - accuracy: 0.9658
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0882 - accuracy: 0.9656
Epoch 35/100
804/804 [==============================] - 3s 3ms/step - loss: 0.0878 - accuracy: 0.9657
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0874 - accuracy: 0.9661
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0879 - accuracy: 0.9658
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0876 - accuracy: 0.9662
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0874 - accuracy: 0.9658
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0867 - accuracy: 0.9660
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0867 - accuracy: 0.9661
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0866 - accuracy: 0.9656
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0861 - accuracy: 0.9663
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0857 - accuracy: 0.9662
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0855 - accuracy: 0.9667
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0853 - accuracy: 0.9667
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0851 - accuracy: 0.9663
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0852 - accuracy: 0.9661
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0852 - accuracy: 0.9659
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0853 - accuracy: 0.9661
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0847 - accuracy: 0.9668
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0846 - accuracy: 0.9669
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0844 - accuracy: 0.9663
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0844 - accuracy: 0.9672
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0843 - accuracy: 0.9674
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0845 - accuracy: 0.9666
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0848 - accuracy: 0.9667
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0847 - accuracy: 0.9670
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0844 - accuracy: 0.9666
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0840 - accuracy: 0.9668
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0839 - accuracy: 0.9668
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0840 - accuracy: 0.9669
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0845 - accuracy: 0.9675
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0842 - accuracy: 0.9674
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0858 - accuracy: 0.9668
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0875 - accuracy: 0.9668
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0856 - accuracy: 0.9663
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0849 - accuracy: 0.9673
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0845 - accuracy: 0.9671
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0839 - accuracy: 0.9671
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0839 - accuracy: 0.9668
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0837 - accuracy: 0.9673
Epoch 73/100
804/804 [==============================] - 3s 3ms/step - loss: 0.0838 - accuracy: 0.9667
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0837 - accuracy: 0.9668
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0835 - accuracy: 0.9662
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0840 - accuracy: 0.9664
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0841 - accuracy: 0.9670
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0833 - accuracy: 0.9674
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0830 - accuracy: 0.9673
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0830 - accuracy: 0.9676
Epoch 81/100

804/804 [==============================] - 3s 3ms/step - loss: 0.0830 - accuracy: 0.9673
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0832 - accuracy: 0.9675
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0827 - accuracy: 0.9674
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0829 - accuracy: 0.9680
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0831 - accuracy: 0.9675
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0831 - accuracy: 0.9673
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0826 - accuracy: 0.9675
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0832 - accuracy: 0.9673
Epoch 89/100
804/804 [==============================] - 3s 3ms/step - loss: 0.0825 - accuracy: 0.9671
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0829 - accuracy: 0.9673
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0827 - accuracy: 0.9686
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0827 - accuracy: 0.9672
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0825 - accuracy: 0.9677
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0825 - accuracy: 0.9670
Epoch 95/100
804/804 [==============================] - 3s 3ms/step - loss: 0.0830 - accuracy: 0.9677
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0833 - accuracy: 0.9674
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0827 - accuracy: 0.9677
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0820 - accuracy: 0.9682
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0827 - accuracy: 0.9670
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0823 - accuracy: 0.9675

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4952 - accuracy: 0.7916 - 695ms/epoch - 3ms/step
Loss: 0.4951522648334503, Accuracy: 0.7916035056114197

In [25]:
# Export our model to HDF5 file
nn_2.save('AlphabetSoupCharity.h5')

C:\Users\akbar\anaconda3\envs\dev\lib\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(